name: Build snapshots

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu-snapshot:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install doctest-dev libpulse-dev portaudio19-dev libjack-jackd2-dev qt6-multimedia-dev

    - name: Configure
      run: >
        cmake -S . -B build
        -G Ninja
        -D CMAKE_BUILD_TYPE=Release
        -D BUILD_SNAPSHOTS=ON
        -D libmt32emu_PACKAGE_TYPE=Runtime
        -D mt32emu-qt_USE_JACK_DYNAMIC_LOADING=ON
        -D mt32emu-qt_USE_PULSEAUDIO_DYNAMIC_LOADING=OFF

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -V

    - name: Package munt monolith
      working-directory: ${{ github.workspace }}/build
      run: cpack -G DEB

    - uses: actions/upload-artifact@v7
      name: Upload munt
      with:
        path: ${{ github.workspace }}/build/munt-*.deb
        archive: false

  build-macos-snapshot:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install doctest portaudio jack qtmultimedia

    - name: Configure
      run: >
        cmake -S . -B build
        -G Ninja
        -D CMAKE_BUILD_TYPE=Release
        -D BUILD_SNAPSHOTS=ON
        -D libmt32emu_PACKAGE_TYPE=Runtime

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -V

    - name: Package munt monolith
      working-directory: ${{ github.workspace }}/build
      run: cpack -G TXZ

    - uses: actions/upload-artifact@v7
      name: Upload munt
      with:
        path: ${{ github.workspace }}/build/munt-*.tar.xz
        archive: false

  build-windows-snapshot:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    env:
      MINGW64_PATH: '/c/msys64/mingw64/bin:/c/msys64/usr/bin'

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: >
        PATH=$MINGW64_PATH:$PATH
        pacman -Sy --noconfirm
        mingw-w64-x86_64-gcc
        mingw-w64-x86_64-doctest
        mingw-w64-x86_64-glib2
        mingw-w64-x86_64-portaudio
        mingw-w64-x86_64-jack2
        mingw-w64-x86_64-qt6-multimedia

    - name: Configure
      run: >
        PATH=$MINGW64_PATH:$PATH
        cmake -S . -B build
        -G Ninja
        -D CMAKE_BUILD_TYPE=Release
        -D BUILD_SNAPSHOTS=ON
        -D libmt32emu_PACKAGE_TYPE=Runtime

    - name: Build
      run: PATH=$MINGW64_PATH:$PATH cmake --build build

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: PATH=$MINGW64_PATH:$PATH ctest -V

    - name: Package munt monolith
      working-directory: ${{ github.workspace }}/build
      run: cpack -G ZIP

    - uses: actions/upload-artifact@v7
      name: Upload munt
      with:
        path: ${{ github.workspace }}/build/munt-*.zip
        archive: false
